### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by rbeezer** [oscarlevin/pandoc-pretext#1]
Continuing from

https://groups.google.com/d/topic/pretext-dev/bS3sAnQgD8c/discussion

Did a pull, am using `pandoc` from Ubuntu packages.

```
rob@lava:/tmp/pan$ pandoc -v
pandoc 1.19.2.4
Compiled with pandoc-types 1.17.0.5, texmath 0.9.4.4, skylighting 0.3.3.1
Default user data directory: /home/rob/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```
Following seems to do the right thing, output looks reasonable.
```
rob@lava:/tmp/pan$ pandoc ~/mathbook/mathbook/README.md -o test.db
```
Now,
```
rob@lava:/tmp/pan$ pandoc ~/mathbook/mathbook/README.md -t ~/mathbook/pandoc-pretext/pretext.lua -o test.ptx
PANIC: unprotected error in call to Lua API ([string "/home/rob/mathbook/pandoc-pretext/pretext.l..."]:13: module 'pandoc.utils' not found:
        no field package.preload['pandoc.utils']
        no file './pandoc/utils.lua'
        no file '/usr/local/share/lua/5.1/pandoc/utils.lua'
        no file '/usr/local/share/lua/5.1/pandoc/utils/init.lua'
        no file '/usr/local/lib/lua/5.1/pandoc/utils.lua'
        no file '/usr/local/lib/lua/5.1/pandoc/utils/init.lua'
        no file '/usr/share/lua/5.1/pandoc/utils.lua'
        no file '/usr/share/lua/5.1/pandoc/utils/init.lua'
        no file './pandoc/utils.so'
        no file '/usr/local/lib/lua/5.1/pandoc/utils.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/pandoc/utils.so'
        no file '/usr/lib/lua/5.1/pandoc/utils.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './pandoc.so'
        no file '/usr/local/lib/lua/5.1/pandoc.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/pandoc.so'
        no file '/usr/lib/lua/5.1/pandoc.so'
        no file '/usr/local/lib/lua/5.1/loadall.so')
```

**Comment by oscarlevin** [comment]
Interesting.  The most recent Pandoc version is 2.7.2.  They must have added support for pandoc.utils since 1.19.

But given that this older version is still out in the wild, it makes sense to try to make the converter as backwards compatible as possible.  I don't *think* I actually need to use pandoc.utils at present, so I removed them.  When you get a chance, let me know if the most recent push solves the issue.  Of course you could upgrade Pandoc, but it would be nice to know if it works before you try that.

**Comment by oscarlevin** [comment]
It looks like pandoc.utils was added in Pandoc 2.0.6, December 28, 2017.

**Comment by rbeezer** [comment]
Success with PTX `README.md` as input!  Also ran it on my LaTeX blurb I give to students who ask for a letter of recommendation.  Seems to have worked well - only hiccup was

```
WARNING: Undefined function 'LineBreak'
```
in the console, and seemingly corresponding
```
<!-- Horizontal Rule Not Implimented -->
```
in the output.

Full speed ahead!  Ping me whenever you want more testing.  (I didn't actually process the PTX output, just looked good visually.  About bedtime here...)  I'll go ahead and close this.

PS - Yes, Ubuntu packaging really does lag badly sometimes....

**Comment by oscarlevin** [comment]
Nice.  Could you send me the latex file: I don't know what elements in LaTeX get interpreted as linebreaks or hrules (which I think are actually two different things which I treated in different ways).  I need to think about what pretext elements these would correspond to.
